### ISSUE TITLE
Random enabling of flags?

### ISSUE THREAD

**Issue by joelr** [FetLife/rollout#89] opened 2016-02-17 04:39 UTC
has anyone seen this happen? We've started to see some flags change from 0 to 100 (ie being enabled), seemingly randomly, eg:

```ruby
irb(main):266:0> namespace.get "feature:my_flag"
=> "0||"
irb(main):267:0> namespace.get "feature:my_flag"
=> "100|1353861,1353862,1348715,1353863|"
```

Time between these 2 commands was maybe 20mins, the code base doesn't touch flag permissions, directly, we just set them via the console.. any thoughts?

**Comment by reneklacan** [comment] 2016-02-17 10:14
Super weird, especially because of `1353861,1353862,1348715,1353863` ... are they real IDs of your users or just random numbers?

**Comment by joelr** [comment] 2016-02-17 22:49
yup, those are real users, they're users who accessed the read side of rollout during that time period.

anyone who tried to access the feature within that period got appended to the above string, but as far as I know that's how rollout works. The more concerning thing is how it flipped from 0 to 100. Still taking a deeper dive..

**Comment by reneklacan** [comment] 2016-02-21 22:20
@joelr any news? would be great if you had code sample reproducing this issue

**Comment by reneklacan** [comment] 2016-03-24 23:07
closing this for now ... feel free to reopen it if you have more info

**Closed by reneklacan** 2016-03-24 23:07 UTC
